language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - jruby
  - rbx-2
gemfile:
  - gemfiles/ar42.gemfile
allow_failures:
  - jruby
  - rbx-2
before_install:
  - sudo apt-get update
  - sudo apt-get install libgeos-dev libproj-dev
